language: ruby
sudo: false
services:
  - redis-server
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
gemfile:
  - gemfiles/sidekiq_3.0.gemfile
  - gemfiles/sidekiq_3.1.gemfile
  - gemfiles/sidekiq_3.2.gemfile
  - gemfiles/sidekiq_3.3.gemfile
  - gemfiles/sidekiq_3.4.gemfile
  - gemfiles/sidekiq_3.5.gemfile
  - gemfiles/sidekiq_4.0.gemfile
  - gemfiles/sidekiq_4.1.gemfile
  - gemfiles/sidekiq_4.2.gemfile
  - gemfiles/sidekiq_5.0.gemfile
  - gemfiles/sidekiq_5.1.gemfile
  - gemfiles/sidekiq_master.gemfile
matrix:
  fast_finish: true
  exclude:
    - gemfile: gemfiles/sidekiq_5.1.gemfile
      rvm: 2.1
    - gemfile: gemfiles/sidekiq_5.0.gemfile
      rvm: 2.1
    - gemfile: gemfiles/sidekiq_master.gemfile

before_install: gem install bundler -v 1.15
script:
  - bundle exec rake spec
  - bundle exec rake spec:sidekiq_testing_integration
